### ISSUE TITLE
Unpacking text failed

### ISSUE THREAD

**Issue by huazuolian** [TesterTesterov/ACPXScriptTool#2]
![image](https://github.com/TesterTesterov/ACPXScriptTool/assets/115382633/1a69f8a3-559b-4fd5-aa85-e526aeaa191e)
When I try to unpack the text, I get an error

**Comment by huazuolian** [comment]
The game is[パニカル・コンフュージョン]

**Comment by TesterTesterov** [comment]
@huazuolian, hello. Post here the script examples.

**Comment by huazuolian** [comment]
Here are the script examples
[script.zip](https://github.com/TesterTesterov/ACPXScriptTool/files/12226424/script.zip)

**Comment by TesterTesterov** [comment]
@huazuolian, okay, done. These formats are compatible, just there are some other commands in use. Try [1.2 release](https://github.com/TesterTesterov/ACPXScriptTool/releases/tag/1.2).
