### ISSUE TITLE
Escu:de engine new version support 

### ISSUE THREAD

**Issue by Aleisster** [TesterTesterov/ACPXScriptTool#3]
Hi. Do you think it would be possible add support for the newest version of Escu:de engine? Escu:de updated the engine after Himeyoku, and now the package script.bin contain two kind of files. When i tried to dissamble one, it appears this message: 
![image](https://github.com/TesterTesterov/ACPXScriptTool/assets/26513330/b93d5194-27bb-41b2-be57-cc0bee03663b)

I'm adding here the scripts of the game I'm testing with. 
[https://vndb.org/v38037](url)
[script.zip](https://github.com/TesterTesterov/ACPXScriptTool/files/12518194/script.zip)

**Comment by TesterTesterov** [comment]
Okay, I shall see...

**Comment by TesterTesterov** [comment]
@Aleisster, hmm, indeed, it is pretty different structurally, but not completely. There is a string encryption added too... Still, I'll add this to the tool, if I have enough time for that. Currently, I have figured almost all of the new structure.

**Comment by TesterTesterov** [comment]
@Aleisster, okay, string encryption is hacked and implemented. Now I'll hack the code itself and implement disassembling/assembling for the new version...

**Comment by TesterTesterov** [comment]
@Aleisster, phew, done. Try [1.3 release](https://github.com/TesterTesterov/ACPXScriptTool/releases/tag/1.3) now. Use *ESCR-NEW* version.

**Comment by Aleisster** [comment]
> @Aleisster, phew, done. Try [1.3 release](https://github.com/TesterTesterov/ACPXScriptTool/releases/tag/1.3) now. Use _ESCR-NEW_ version.

Indeed it works perfectly now! Thanks.

**Comment by Aleisster** [comment]
Hi again @TesterTesterov sorry, I wasn't sure if I should reopen this issue for this question. I'm translating the game I asked support for last time, but I have a little problem. Since scripts are encoded in shift jis, I'm using a modded font to display the special characters of my language. But when I do that, the game creates a weird spacing beetween the displayed special character (originally a shift jis character) and the next character. I'm adding a screenshot. Do you have any advice of how can I solve this? 
![image](https://github.com/TesterTesterov/ACPXScriptTool/assets/26513330/2e037639-9057-4d19-a4a3-4a919e5d9e66)

PD: The special character is "í" word, the complete word is "sucedía".

**Comment by TesterTesterov** [comment]
@Aleisster, the reason is because that character in Shift-JIS is full-width, while others are half-width. You need to edit the font that way so you move special characters glyphes to places some other half-width characters occupy. For example, move í to symbol = so then you type = in script í display. After that, change all í in script to =. The same way with others.

**Comment by Aleisster** [comment]
@TesterTesterov Thank you for your reply!  Also I have noticed that when I try to export the scripts with utf8 coding, the program exports in shift jis. Is this because that's how the game works or maybe it is a bug? 
Also, the character's names are not stored in the scripts?

**Comment by Aleisster** [comment]
@TesterTesterov Also one more thing, sorry. I get this error while assambling new script: Expecting value: line 1 column 2 (char 1)
but to be honest, I don't know what would be causing this. I'm leaving here original script file and edited text. 
[a_prologue_01_02_H_original.zip](https://github.com/TesterTesterov/ACPXScriptTool/files/13782376/a_prologue_01_02_H_original.zip)

[a_prologue_01_02_H_text.zip](https://github.com/TesterTesterov/ACPXScriptTool/files/13782380/a_prologue_01_02_H_text.zip)
Thanks in advance.
